export const DEPLOY_ENV = process.env.REACT_APP_DEPLOY_ENV;
export const NODE_ENV = process.env.NODE_ENV;
export const FIREBASE_AUTH_EMULATOR_PORT =
  process.env.REACT_APP_FIREBASE_AUTH_EMULATOR_PORT;
export const FIREBASE_FIREBASE_EMULATOR_PORT =
  process.env.REACT_APP_FIREBASE_FIRESTORE_EMULATOR_PORT;
