name: Netlify Deploy Preview (Dev)

on:
  pull_request:
    branches:
      - "dev"
    types:
      - 'opened'
      - 'edited'
      - 'synchronize'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    name: 'Deploy Preview to Netlify'
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:          
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
