name: Frontend CI

on:
  pull_request:
    branches:
      - "dev"
    types:
      - "opened"
      - "edited"
      - "synchronize"

jobs:
  build_test:
    runs-on: ubuntu-latest
    name: "Build and Test application"

    strategy:
      matrix:
        node-version: [16.13]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    needs: build_test
    runs-on: ubuntu-latest

    name: "Deploy Preview to Netlify"
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
