name: "Deploy Production Branch to Netlify"

on:
  release:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD }}
          NETLIFY_DEPLOY_MESSAGE: "Production deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
